### ISSUE TITLE
Install/run instructions don't work for Qt 4

### ISSUE THREAD

**Issue by jlmuir** [mxcube/mxcubeqt#153] opened 2017-01-30 23:24 UTC
The [Qt 4 install and run instructions](https://github.com/mxcube/mxcube/blob/master/docs/source/installation_instructions_qt4.rst) say that the last command argument to `bin/mxcube` should be `-qt3` or `-qt4`, but I get the following error when I use `-qt4` as the last argument:

```
Traceback (most recent call last):
  File "/home/jlmuir/devel/mxcube-2/bin/mxcube", line 22, in <module>
    from BlissFramework import startGUI
  File "/home/jlmuir/devel/mxcube-2/BlissFramework/startGUI.py", line 12, in <module>
    from qt import *
ImportError: No module named qt
```

If I use `qt4` as the last argument instead (i.e., remove the leading dash), then it starts OK.

I don't know if the instructions are wrong (i.e., should say `qt3` or `qt4` without the leading dashes) or if the source code is wrong (e.g., in `bin/mxcube` where it does `if sys.argv[-1].upper() in ("QT4", "QT5")`).

This is with the master branch on Ubuntu 14.04 LTS.

**Comment by IvarsKarpics** [comment] 2017-01-31 06:05
Hi @jlmuir ,

Thanks for the bug report. I noticed this error as well. Few commits ago a new QtImport module was introduced that detects PyQt version (4, 5 or PySide). With this module there will be no need to pass Qt version argument.
I prepared several pull requests to the BlissFramework and mxcube. After merging them in master  this bug should be fixed.

**Comment by IvarsKarpics** [comment] 2017-02-01 13:24
Hi @jlmuir ,

Pull requests #152 , mxcube/BlissFramework#19, mxcube/HardwareObjects#180 and mxcube/HardwareRepository#14 should solve the bug.
Could you please update all repositories and try it?

**Comment by jlmuir** [comment] 2017-02-01 20:11
I can't update the submodules:

```
$ git fetch
$ git merge origin/master
$ git submodule update
Submodule path 'BlissFramework': checked out '33dde2ca05bdc3a40721363a8132e8ffd2d350ca'
fatal: reference is not a tree: 801cdc11c4d30a90222631c9d5293644fa5a11ea
Submodule path 'HardwareRepository': checked out 'e0f524d2c4c58b345a3a51f208b0413d755ced0c'
Unable to checkout '801cdc11c4d30a90222631c9d5293644fa5a11ea' in submodule path 'HardwareObjects'
```

**Comment by mguijarr** [comment] 2017-02-02 08:31
Hi @jlmuir and thanks for the report.

The problem is solved since we merged [this PR](https://github.com/mxcube/HardwareObjects/pull/181/commits), 11 hours ago.

**Closed as completed** 2017-02-02 08:32 UTC
Labels: bug
